### ISSUE TITLE
SQLite source url changes according to sqlite version

### ISSUE THREAD

**Issue by luisparravicini** [stockrt/sqlite3-android#2]
The download url for SQLite has the year of the release as part of the path. The makefile is using `2014` in `SQLITE_URL` and thus, to download a recent version you have to change `SQLITE_VERSION` and the year inside `SQLITE_URL`.

I think the documentation should mention this, or, have a way to automatically know the year that should be used in the url according to the value in `SQLITE_VERSION`.

**Comment by FabianFrank** [comment]
:+1:
